### ISSUE TITLE
Automatic LED brightness algorithm

### ISSUE THREAD

**Issue by LukaBanovic** [IRNAS/pulseox-firmware#1]
![brightness_adjustment](https://user-images.githubusercontent.com/14543226/42219068-e50c001c-7eca-11e8-8267-3a4e325834ca.png)

**Comment by LukaBanovic** [comment]
IR step = 20
RED step = 500

**Comment by LukaBanovic** [comment]
Test: do not include the last condition, terminate the brightness changing loop after a fixed time, observe the SQI behaviour on a plotted graph. This way we can get optimal SQI values.

**Comment by vid553** [comment]
![brightness_adjustment 1](https://user-images.githubusercontent.com/27289158/43064904-82e60cde-8e60-11e8-8c13-3201a37b2d7e.png)
